### ISSUE TITLE
#T2 - Recolectar recursos gráficos.

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#27]
Recolectar imágenes, botones, figuras, e íconos (carrito, redes, etc) para el sitio según brief. 
Características:  rgb -      72 dpi.  
un sitio de desacarga gratuita es: www.freepik.com, tiene límite diario. 
(hoteles, destinos, personas felices de vacaciones, maletas, aviones, colectivos, marcas amigas, etc).

**Comment by PatriciAleSolis** [comment]
Buscando recursos

**Comment by DamianGuidone** [comment]
Aporto con un recurso interesante para íconos a tener en cuenta, es el uso de una herramienta para ahorrar espacio y por ende demoras en la carga de nuestra páginas. Es simplemente un tipo de font representado por íconos, existen varios en internet, propongo éste como ejemplo: https://fontawesome.com/v5/cheatsheet
