### ISSUE TITLE
#T4 - Aside. Sponsors

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#29]
Aside- construir con sponsors.

**Comment by PatriciAleSolis** [comment]
Listo

**Comment by PatriciAleSolis** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Descripción</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <section id="description">
        <div class="container">
            <h2 class="display-2">Descripción</h2>
            <p>Te recontramos con tus sueños.</p>
            <div class="imagen1">
                <img src="./imagenes/viaje.jpg" alt="viaje">
            </div>
        </div>
    </section>

    <section id="servicios">
        <div class="container">
            <h2 class="display-2">Nuestros servicios</h2>
            <div class="feature-box">
                <div class="description-row">
                    <div class="description-box">
                        <img src="./imagenes/viaje.jpg" alt="sex">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam dolores animi, vero eos
                            beatae quidem! </p>
                    </div>
                </div>
            </div>
            <div class="feature-box">
                <div class="description-box">
                    <img src="./imagenes/viaje.jpg" alt="sex">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam dolores animi, vero eos beatae
                        quidem! </p>
                </div>
            </div>
            <div class="feature-box">
                <div class="description-box">
                    <img src="./imagenes/viaje.jpg" alt="sex">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam dolores animi, vero eos beatae
                        quidem!</p>
                </div>
            </div>
        </div>
    </section>

    <section id="about">
        <div class="container">
            <div class="about-image">
                <img src="./imagenes/viaje.jpg" alt="sex">
            </div>
            <div class="about-text">
                <h3>Lorem ipsum dolor sit amet.</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores nihil reiciendis debitis beatae,
                    ducimus voluptates est id itaque consequatur dolorem consectetur deleniti eveniet et nulla.</p>
            </div>
        </div>
    </section>
    <div class="lower-container container">
        <section class="stats">
            <div class="flex">
                <div class="stat">
                <i class="fa fa-folder-open fa-2x" aria-hidden="true"></i>
                <h3 class="title">Es solo una columna</h3>
                <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <div class="stat">
                <i class="fa fa-graduation-cap fa-2x" aria-hidden="true"></i>
                <h3 class="title">otra información</h3>
                <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <div class="stat">
                <i class="fa fa-credit-card-alt fa-2x" aria-hidden="true"></i>
                <h3 class="title">Aca va otra cosa</h3>
                <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
            </div>
        </section>
        <aside>    
        <section class="testimonials">
            <div class="container">
                <div class="testimonial grid-3">
                <div class="card">
                    <div class="circle">
                    <img src="./imagenes/image-avatar.png" alt="">
                    </div>
                    <h3>Empresa de tranporte</h3>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Omnis, excepturi ratione! Consequatur, ea! Nesciunt ad ratione ullam, quo fugiat temporibus, adipisci velit consectetur delectus cupiditate natus soluta quasi, exercitationem aut.</p>
                </div>
                    <div class="card">
                    <div class="circle">
                    <img src="./imagenes/image-avatar.png" alt="">
                    </div>
                    <h3>Empresa de hopedaje</h3>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatem dolor necessitatibus nam minus veritatis iure labore libero illum ut dolore, cum, dicta quos vero quaerat dolorem eum excepturi tempore ab?</p>
                    </div>
                    <div class="card">
                    <div class="circle">
                    <img src="./imagenes/image-avatar.png" alt="">
                    </div>
                    <h3>Empresa de comidas</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam culpa autem placeat labore natus accusantium fuga officia, asperiores aliquid obcaecati, sequi incidunt error dolores, accusamus ducimus quae temporibus quas commodi.</p>
                    </div>
                </div>
            </div>
        </section>
        </aside>

    <footer>
            <div class="container grid-3">
                <div class="copyright">
                <h3>Travel Easy</h3>
                <p>Copyright &copy; 2022</p>
                </div>
                <nav class="links">
                <ul>
                    <li><a href="" class="outline">INICIO</a></li>
                    <li><a href="" class="outline">NOSOTROS</a></li>
                    <li><a href="" class="outline">CATEGORIAS</a></li>
                </ul>
                </nav>
                <div class="profiles">
                <a href=""><em class="fab fa-twitter fa-2x"></em></a>
                <a href=""><em class="fab fa-instagram fa-2x"></em></a>
                <a href=""><em class="fab fa-facebook fa-2x"></em></a>
                <a href=""><em class="fab fa-whatsapp fa-2x"></em></a>
                </div>
            </div>
    </footer>

</body>
</html>`
