### ISSUE TITLE
Idear mapa de sitio

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#3]
Crear un mapa se sitio para , a partir de allí tener definidas las secciones sobre las cuáles trabajar.

**Comment by DamianGuidone** [comment]
#Mapa del sitio


El mapa del sitio fué creado en base a los requerimientos reflejados en las historias de usuarios listadas en la documentación, y plasmado en un archivo png en el directorio Documentación dentro del main.

link del mapa: [IR AL MAPA DEL SITIO](https://github.com/AnahiNicoli/FullStack_ISPC/blob/main/Documentaci%C3%B3n/MapaSitio_Easy_Travel.png)
