### ISSUE TITLE
#T6 - Crear redes (reales). 

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#31]
Generar perfiles de facebook, instagram, twitter, tik tok de la compañía Easy Travel y ÁREA 58.

**Comment by GabrielReyes19** [comment]
Se creo un correo electrónico para notificaciones de la agencia de viajes easytravelgroup@gmail.com

**Comment by GabrielReyes19** [comment]
Se creo para promocionar los destinos la página en Facebook con el nombre de viaja facil https://www.facebook.com/profile.php?id=100086248587191

**Comment by GabrielReyes19** [comment]
Se creo cuenta de Instagram para promocionar viajes @easytravel.22

**Comment by GabrielReyes19** [comment]
https://instagram.com/easytravel.22?igshid=YmMyMTA2M2Y=
