### ISSUE TITLE
#T7 - Footer.

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#32]
Crear footer con:
-Info legal/arrepentimiento/preguntas frecuentes/términos y condiciones.
-Redes (íconos y vínculos).
-Datos de contacto.

**Comment by PatoFlowers** [comment]
En proceso

**Comment by PatoFlowers** [comment]
Listo, falta agregar links que corresponden a otros issues (redes sociales y form de contacto).
