### ISSUE TITLE
#T9 - Crear modelo relacional y base de datos.

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#34]
Crear modelo relacional y base de datos para almacenar usuarios con historial, productos y ofertas y que se pueda consultar en cualquier momento de manera ágil y rápida (comentarios de feedback?). Requisito: editable.

“Yo como administrador quiero una base de datos para almacenar usuarios, historias de usuarios, productos y ofertas para poder usar esos datos y ofrecer un servicio más especializado.”

**Comment by DamianGuidone** [comment]
Doy comienzo a la tarea asignada, comenzaré con el modelo entidad relación

**Comment by DamianGuidone** [comment]
Diagrama Entidad Relación:



![IR A DIAGRAMA](https://user-images.githubusercontent.com/69549331/194940191-7a090db6-3839-4df3-8069-28ec0894d210.png)

**Comment by DamianGuidone** [comment]
Script de cración de Base de Datos:

![Acceso al script](https://github.com/AnahiNicoli/FullStack_ISPC/blob/main/Backend/easy_Travel/db.sql)
