### ISSUE TITLE
#T18 - Diagrama de caso de uso. 

### ISSUE THREAD

**Issue by AnahiNicoli** [AnahiNicoli/FullStack_ISPC#43]
Seguimiento de los casos de uso desarrollados: 

https://docs.google.com/spreadsheets/d/1iyxEkKcLWlA7BAQCPTQz1MRhyJ_k8ExDdEvnEc0pCxU/edit

**Comment by PatriciAleSolis** [comment]
[Caso de uso.pdf](https://github.com/AnahiNicoli/FullStack_ISPC/files/9882612/Caso.de.uso.pdf)

**Comment by PatriciAleSolis** [comment]
![casosdeuso1](https://user-images.githubusercontent.com/106406283/201350730-4d4e3e2a-1dc5-4cac-881b-3c90ee38599a.jpeg)
